# Standard-Parameter
output_dir: "out"
altitude_mode: "clampToGround"
default_altitude: 0.0
force_polygon: true
close_rings: true
add_z_if_missing: true
optimize_angle: "mrr"
tile:
  enabled: false
  max_edge_m: 500
